
app = "ns-api"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "15s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "canary"

[processes]
  app = "gunicorn --forwarded-allow-ips '*' -b :8080 -w 3 --max-requests 1000 --max-requests-jitter 100 -k uvicorn.workers.UvicornWorker app.main:app"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "1m0s"
    timeout = "2s"
    grace_period = "20s"
    restart_limit = 0
    method = "get"
    path = "/"
    protocol = "http"
